CREATE DATABASE IF NOT EXISTS barangay_bis;
USE barangay_bis;


CREATE TABLE IF NOT EXISTS residents (
id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
middle_name VARCHAR(100),
dob DATE,
gender ENUM('Male','Female','Other'),
civil_status VARCHAR(50),
place_of_birth VARCHAR(200),
address VARCHAR(255),
household_no VARCHAR(50),
phone VARCHAR(50),
email VARCHAR(100),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);